version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/npm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/yarn"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/pnpm"
    schedule:
      interval: "weekly"
